### ISSUE TITLE
What can be wrong if subscription data doesn't reach client side?

### ISSUE THREAD

**Issue by k1tzu** [tgdn/react-starter-kit-subscription#3]
With the code like
```
      PubSub.publish('messageCreated', {
        messageCreated: {text: "hello world"}
      });
```
and
```
subscription onMessageCreated {
  messageCreated {
    id
    text
    createdAt
    updatedAt
  }
}
```

I get  null in Messages.js
```
        updateQuery: (prev, { subscriptionData }) => {
             console.log(subscriptionData.data.messageCreated);
```
in websockets conversation I see the request
```
{"id":"2","type":"start","payload":{"query":"subscription onMessageCreated {\n messageCreated {\n id\n text\n createdAt\n updatedAt\n __typename\n }\n}\n","variables":{},"operationName":"onMessageCreated"}}
```
and reply
```
{"type":"data","id":"1","payload":{"data":{"messageCreated":null}}}
```

Can you please tell me - how to debug it? Where it can lose the message along the way?
Can't find it:(

**Comment by k1tzu** [comment]
The problem was simple but it ate some lifetime - code for subscription lacks ```resolve:``` part
``` 
Subscription: {
    messageCreated: {
              resolve: messageData => messageData,
```

**Comment by tgdn** [comment]
Submit a pull request if needed. Are you talking about https://github.com/tgdn/react-starter-kit-subscription/blob/master/src/data/schema.js#L32 ?

**Comment by k1tzu** [comment]
Yes! Without ```resolve:``` it was not working for me.

**Comment by tgdn** [comment]
Although you didn't use `PubSub.asyncIterator('messageCreated')` in your code?

**Comment by k1tzu** [comment]
No I took your code and it wasn't working without the resolve part. It returned just the event "messageCreated" without the data.
The working code is
```
  Subscription: {
    messageCreated: {
      resolve: messageData => messageData,
      subscribe: () => {
        return PubSub.asyncIterator('messageCreated');
      },
   }
 }
```

by the way - do you know where the component gets this.props.data and this.props.data.subscribeToMore from?

**Comment by tgdn** [comment]
Right on.

Have a look at  [subscribeToMore](http://dev.apollodata.com/react/subscriptions.html#subscribe-to-more) and [the structure of the data prop](http://dev.apollodata.com/react/queries.html#default-result-props)
